---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Content
- type: directory
  path: posts
  label: Posts
  create: all
  match: "**/*"
- type: directory
  path: ''
  label: Pages
  create: documents
  match: "**"
- type: heading
  label: Data
- type: document
  path: _data/metadata.json
  label: Global Meta
upload_dir: ''
public_path: https://res.cloudinary.com/joelgoodman/image/upload
front_matter_path: ''
use_front_matter_path: true
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run forestry:preview
